### ISSUE TITLE
Fehler in der Login-Prozedur

### ISSUE THREAD

**Issue by derhelge** [JKoblitz/osiris#24]
Hallo aus Bochum,

ich glaube, dass mir nach der Installation ein Fehler in der Login-Prozedur aufgefallen ist: Meldet sich ein LDAP-Benutzer "user" mit seinem Passwort an, erhält er die LDAP-Attribute von einem anderen Benutzer, sofern es zB "auser" gibt:
In _login.php wird in newUser() -> getUser() der LDAP-Filter angegeben mit: `(|(samaccountname=*$name*))` und das erste Ergebnis genommen. Das ist hier also "auser" und nicht "user".

Soweit ich sehe, hat das interessante Seiteneffekte: Nach jedem Login mit "user" wird, ein neuer User mit den Attributen (inklusive username) von "auser" angelegt.

Ich habe das Problem nicht weiter untersucht, denn  `(|(samaccountname=$name))`  nimmt zwar die richtigen Attribute aber erzeugt nach jedem Login einen neuen user-Datensatz.

Viele Grüße
Helge

**Comment by JKoblitz** [comment]
Hallo Helge,
sorry für den langen Delay. Ich hatte Probleme, den Fehler zu reproduzieren, denke aber, dass ich ihn fixen konnte. Auch das Problem mit den Duplizierenden Nutzern müsste gelöst sein. Falls möglich also bitte ein Update machen. Falls das Problem dennoch auftritt, bitte umgehend Bescheid geben, dann schaue ich es mir noch mal an. Wäre super lieb, wenn du auch Bescheid geben könntest, falls das Problem nicht mehr auftritt, dann schließe ich das Ticket.

Viele Grüße aus Braunschweig
Julia

**Comment by derhelge** [comment]
Hallo Julia,

ja danke, aber wie gesagt: `(|(samaccountname=$name))` nimmt zwar die richtigen Attribute aber erzeugt nach jedem Login einen neuen user-Datensatz. Das habe ich auf die Schnelle nicht gefixed bekommen.

**Comment by JKoblitz** [comment]
Hallo Helge, 

hast du das noch mal mit dem aktuellen Code ausprobiert? Denn ich hatte gehofft, mein Fix #93f830b92e114a7b34d41e16f4a8247dfe37a6aa hätte das Problem mit den duplizierten Usern gelöst. 

Falls nicht, muss ich noch mal genauer nachschauen, wie die LDAP-Prozedur genau zu diesem Fehler führt. 

Viele Grüße 
Julia
